monorail.jsonを更新
codeforchiba/covid19 pull request #269
Opened 2020-11-19 03:09 UTC by seitaro1227

## 📝 関連issue / Related Issues

- close #{ISSUE_NUMBER}

## ⛏ 変更内容 / Details of Changes

- xxxxxx
- xxx

## 📸 スクリーンショット / Screenshots

2020-11-21 00:01 UTC, misopeso requested changes
1点気になるデータがあるので、確認してください。

2020-11-21 00:01 UTC, misopeso commented on data/monorail.json
> +    "date": "2020-11-19 12:06",
`date` のフォーマットが変わってますが、問題ないですか？

2020-11-22 02:24 UTC, k-hata commented on data/monorail.json
> +    "date": "2020-11-19 12:06",
更新日付はスクリプトを動かした日を手入力するようになっていて、その時の入力ミスのようです。
この値は表示しているだけなので今のままでも問題ありませんが、これまでどおりのフォーマットに修正しました。
根本対処としては、実行時のシステム日付取ってフォーマット変換かけたほうがこのようなミスがなくなってよいですね。

2020-11-22 15:54 UTC, seitaro1227 commented on data/monorail.json
> +    "date": "2020-11-19 12:06",
@misopeso @k-hata 

すいません。修正ありがとうございます。
自動で現在日付を入るようにしておきます。

2020-11-30 12:21 UTC, closed without merging

2020-11-30 12:21 UTC, seitaro1227 commented
今日付のデータがあるためリジェクト