Feature/convert monorail json
codeforchiba/covid19 pull request #563
Opened 2021-07-07 12:57 UTC by k-hata

## 👏 解決する issue / Resolved Issues
- close #531

## ⛏ 変更内容 / Details of Changes
- GitHubActionsにより毎晩11時に起動
- GoogleDriveの「10_千葉市受領データ」を検索し、(更新の有無に関わらず)最も新しいモノレールデータファイル(excel)からmonorail.jsonを生成
- dataフォルダ配下にmonorail.jsonを格納

2021-07-13 02:11 UTC, misopeso requested changes
全体的なところは良いと思いますが、細かいところ確認お願いしますー

2021-07-13 02:11 UTC, misopeso commented on .github/workflows/convert_monorail.yml
> +        run: pip install -r tool/requirements.txt
`pip` のお作法はよくしりませんが、必要なライブラリの定義ファイルですよね。`npm` とかと一緒でルート直下でいいんじゃないかな、と思うんですが、どうでしょう。

2021-07-13 02:11 UTC, misopeso commented on .github/workflows/convert_monorail.yml
> +          git clean -f
この 2行って、なんのためにありますか？

2021-07-13 02:11 UTC, misopeso commented on .github/workflows/convert_monorail.yml
> +          git status | grep "modified:   data/monorail.json" && git add data/monorail.json \
`modified:` 以降のスペースって、ないと `grep` でひっかからない感じです？

2021-07-13 11:45 UTC, k-hata commented on .github/workflows/convert_monorail.yml
> +        run: pip install -r tool/requirements.txt
そうですね。ルート直下に動かします。

2021-07-13 11:52 UTC, k-hata commented on .github/workflows/convert_monorail.yml
> +          git clean -f
ああやっぱり不思議におもいますよね。
後続の「pascalgn/automerge-action@v0.14.2」君がgit addしたファイル以外に変更されたJupyterNotebookや、その中で取得したGoogleDriveのファイルを全部含めてマージ&コミットしてくれるので(余計なことを)意図的にデータ削除してます。

2021-07-13 12:31 UTC, k-hata commented on .github/workflows/convert_monorail.yml
> +          git status | grep "modified:   data/monorail.json" && git add data/monorail.json \
ここはコピーしたままファイル名くらいしかいじってませんが、確かに空白は余計ですね。
data.jsonだけヒットすればいいのでmodifiedも削除しました。

2021-07-13 14:59 UTC, misopeso requested changes
1コだけ気になる修正があるので、ここが OK なら良さそうです！

2021-07-13 14:59 UTC, misopeso commented on .github/workflows/convert_monorail.yml
> +  - cron: '00 14 * * *'
ここが変わっちゃっているのが気になりますが、これであってます？？？

2021-07-13 23:34 UTC, k-hata commented on .github/workflows/convert_monorail.yml
> +  - cron: '00 14 * * *'
(差分見て)変更表示されているのは2箇所で、どちらも問題ないという認識です。
workflow_dispatchの行は、ファイル不具合等で実行できなかった場合に、ファイル修正後、手動で再実行できるように追加してあります。
cronの分指定は00でも0でもどちらでも動きます。正しく自動実行できるか書き直して試した際に戻し忘れたようですが、振る舞いとしては変わらないです。

2021-07-13 23:55 UTC, misopeso commented on .github/workflows/convert_monorail.yml
> +  - cron: '00 14 * * *'
`workflow_dispatch` が必要なのは理解しました。cron のところは、インデント不要ですか？

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

2021-07-14 03:21 UTC, k-hata commented on .github/workflows/convert_monorail.yml
> +  - cron: '00 14 * * *'
不要です。forkした私のリポジトリで、同じもの動いてますので。

2021-07-14 14:03 UTC, misopeso approved these changes
LGTM!

2021-07-14 14:06 UTC, merged