リトライ間隔とリトライ回数の設定追加
codeforchiba/covid19 pull request #578
Opened 2021-07-15 16:15 UTC by k-hata

## 👏 解決する issue / Resolved Issues
- close #577 

## ⛏ 変更内容 / Details of Changes
- NetlifyのDeploy終了を待ってPull Request Mergeを実行するように、
mergeable_state チェックのリトライ間隔とリトライ回数を追加した。
MERGE_RETRIES: "10"(回数)
MERGE_RETRY_SLEEP: "60000"(ms)

## その他
これでうまく動作することが確認できれば、GithubActionsの実行回数を日次から週次(毎週水曜)に変更し、無意味な実行回数を削減する予定。

2021-07-15 22:52 UTC, misopeso requested changes
1点ご確認いただけますとー

2021-07-15 22:52 UTC, misopeso commented on .github/workflows/convert_monorail.yml
> +          MERGE_RETRY_SLEEP: "60000"
この Job 全体のタイムアウトとして `timeout-minutes: 10` が設定されているので、この設定値にするなら全体のタイムアウト設定を伸ばしておいたほうがいいですね。

2021-07-15 23:23 UTC, k-hata commented on .github/workflows/convert_monorail.yml
> +          MERGE_RETRY_SLEEP: "60000"
全体のタイムアウト時間を15分に延長しました。

2021-07-16 08:18 UTC, misopeso approved these changes
LGTM!

2021-07-16 08:18 UTC, merged